language: cpp
os: osx

osx_image:
  - xcode6.4
  - xcode7.3
  - xcode8
  - xcode8.3
  - xcode9

script:
  - sw_vers
  - brew info qt5
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install qt5
  - $(brew --prefix qt5)/bin/qmake --version
